<a href="https://colab.research.google.com/github/MichelaPascale/AI_Python/blob/main/Intro%20al%20ML%20con%20Python%20-%20Lezione%20del%2022%20Aprile%202021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Introduzione al Machine Learning con Python**

In [ ]:
#Scikit-learn è uno dei package più utilizzati per il machine learning

###**Iris**

Dataset che contiene 150 esempi di fiori Iris descritti da 4 features


In [3]:
#Iris è incluso in Scikit-learn nel modulo datasets
from sklearn.datasets import load_iris
iris_dataset = load_iris()  #una sorta di dizionario

In [6]:
print("Keys of iris_dataset: \n", iris_dataset.keys())

Keys of iris_dataset: 
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [8]:
print(iris_dataset['DESCR'][:193] + "\n...")  #stampiamo solo i primi 193

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [17]:
print('Target names: ', iris_dataset['target_names'])

Target names:  ['setosa' 'versicolor' 'virginica']


In [16]:
print('Features name: \n', iris_dataset['feature_names'])

Features name: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
print('Type of data: ', type(iris_dataset['data'])) #un array con 150n righe e 4 colonne

Type of data:  <class 'numpy.ndarray'>


In [13]:
print('Shape of data: ', iris_dataset['data'].shape)

Shape of data:  (150, 4)


In [15]:
print('First five rows of data: \n', iris_dataset['data'][:5])

First five rows of data: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [18]:
print('Shape of target: ', iris_dataset['target'].shape)

Shape of target:  (150,)


In [19]:
print('Target: ', iris_dataset['target'])

Target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


####**Split**

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)  
#questa funzione fa il mescolamento e il 75% lo mette nel training set e il 25% nel test set

In [23]:
print('x_train shape: ', x_train.shape)
print('y_train shape: ', y_train.shape)

x_train shape:  (112, 4)
y_train shape:  (112,)


In [24]:
print('x_test shape: ', x_test.shape)
print('y_test shape: ', y_test.shape)

x_test shape:  (38, 4)
y_test shape:  (38,)


In [25]:
x_train[:5]

array([[5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3]])

In [27]:
y_test[:5]

array([2, 1, 0, 2, 0])

####**K-Nearest Neighbors**

In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)  #specifico il numero dei neighbors e istanzio knn nella variabile

In [29]:
#addestramento del modello -> funzione fit
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [32]:
import numpy as np

#voglio capire se è in rado di fare una classificazione di un nuovo fiore
x_new = np.array([[5, 2.9, 1, 0.2]])  #nuovo fiore con questi valori

In [33]:
prediction = knn.predict(x_new)  #predizione della classe
print('Prediction: ', prediction)
print('Predicted target name: ', iris_dataset['target_names'][prediction])

Prediction:  [0]
Predicted target name:  ['setosa']


#####**Valutazione del modello**

In [34]:
y_pred = knn.predict(x_test)
print('Test set prediction: \n', y_pred)

Test set prediction: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [36]:
#per valutare la bontà tocca confrontare y_pred con x_test

print('Test set score: {:.2f}'.format(np.mean(y_pred == y_test)))  
#faccio la media di tutti i casi ottenendo la percentualoe degli esempi del test set che sono stati classificati correttamente 

Test set score: 0.97


In [37]:
print('Test set score: {:.2f}'.format(knn.score(x_test, y_test)))  #lo score fa tutti i conti da solo e valuta l'accuratezza del classificatore

Test set score: 0.97
