<a href="https://colab.research.google.com/github/MichelaPascale/AI_Python/blob/main/NumPy%20-%20Lezione%2024%20Marzo%202021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LEZIONE DEL 24 MARZO 2021 - (INTRO PYTHON) - INTELLIGENZA ARTIFICIALE**

##**NumPy**

### **Calcolo numerico**

In [1]:
a = [1, 4, 2, 8, 3]
b = [3, 2, 4, 5, 6]

In [2]:
# Voglio fare il prodotto tra gli elementi delle due liste

# SENZA NUMPY
c = []
for i in range(5):
  c.append(a[i]*b[i])

print(c)

[3, 8, 8, 40, 18]


In [3]:
# CON NUMPY
import numpy as np

In [4]:
a = np.array([1, 4, 2, 8, 3])
b = np.array([3, 2, 4, 5, 6])

c = a * b
print(c)

[ 3  8  8 40 18]


### **Array di Dati**

**Array mediante Liste Python**

In [5]:
v = [0.56, 0.75, 1.0, 1.5, 2.0]

m = [v, v, v]
print(m)

[[0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0]]


In [6]:
m[1]

[0.56, 0.75, 1.0, 1.5, 2.0]

In [7]:
m[1][0]

0.56

In [9]:
v1 = [0.5, 1.5]
v2 = [1,2]

m = [v1, v2]
print(m)

[[0.5, 1.5], [1, 2]]


In [12]:
c = [m, m]
print(c)

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]


In [13]:
c[1][0][1] #1.5

1.5

In [14]:
v = [0.56, 0.75, 1.0, 1.5, 2.0]

m = [v, v, v]
print(m)

[[0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0]]


In [15]:
v[0]

0.56

In [17]:
v[0] = 'Prova'

print(v)
print(m)  #la nuova assegnazione ha avuto le conseguenze anche su m, poiché il riferimento è sempre allo stesso oggetto 

['Prova', 0.75, 1.0, 1.5, 2.0]
[['Prova', 0.75, 1.0, 1.5, 2.0], ['Prova', 0.75, 1.0, 1.5, 2.0], ['Prova', 0.75, 1.0, 1.5, 2.0]]


In [19]:
# Come evitare ciò? Ne faccio una copia

from copy import deepcopy

In [20]:
v = [0.56, 0.75, 1.0, 1.5, 2.0]

m = 3 * [deepcopy(v),]  #v ripetuto 3 volte
print(m)

[[0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0]]


In [21]:
v[0] = 'Prova'

print(v)
print(m) #m in questo modo non viene cambiata

['Prova', 0.75, 1.0, 1.5, 2.0]
[[0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0], [0.56, 0.75, 1.0, 1.5, 2.0]]


**Array Class in Python**

In [25]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
print(v)

[0.5, 0.75, 1.0, 1.5, 2.0]


In [23]:
import array

In [26]:
a = array.array('f', v)
print(a)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])


In [27]:
a.append(0.5)
print(a)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])


In [29]:
#Se voglio aggiungere gli elementi di un'altra lista
# => concatenazione

a.extend([5.0, 6.75])  #concatenazione 
print(a)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])


In [30]:
print(2*a)  #come le liste => duplicazione

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])


In [31]:
a.append('string')

TypeError: ignored

In [33]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

###**NumPy Arrays**

In [34]:
import numpy as np

In [35]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [36]:
type(a)

numpy.ndarray

In [37]:
a = np.array(['a', 'b', 'c'])
type(a)

numpy.ndarray

In [38]:
a = np.arange(2, 20, 2)  # da 2 (incluso) a 20 (escluso) con passo di 2
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [40]:
a = np.arange(8, dtype=np.float)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [41]:
a[5:]

array([5., 6., 7.])

In [42]:
a[:2]

array([0., 1.])

In [43]:
a.sum()  #somma di tutti gli elementi di a

28.0

In [44]:
a.std() #deviazione standard (?)

2.29128784747792

In [45]:
# Somma comulativa
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [46]:
l = [0, 0.5, 1.5, 3., 5.]
l

[0, 0.5, 1.5, 3.0, 5.0]

In [47]:
2 * l

[0, 0.5, 1.5, 3.0, 5.0, 0, 0.5, 1.5, 3.0, 5.0]

In [50]:
print(a)

[0. 1. 2. 3. 4. 5. 6. 7.]


In [48]:
2 * a  #in questo caso moltiplico ogni elemento per 2 e non la duplicazione

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [49]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [51]:
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [52]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [53]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [54]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [55]:
np.sqrt(2.5)

1.5811388300841898

In [56]:
import math

In [57]:
math.sqrt(2.5)  #ma math non posso applicarlo ad un array

1.5811388300841898

In [58]:
%timeit np.sqrt(2.5)

The slowest run took 92.41 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 836 ns per loop


In [59]:
%timeit math.sqrt(2.5)  #vantaggio prestazionale

The slowest run took 35.58 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 5: 93.2 ns per loop


**Dimensioni multiple**

In [60]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [62]:
b = np.array([a, a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [63]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [64]:
b[1]

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [65]:
b[0, 2]

2.0

In [66]:
b[0][2]

2.0

In [67]:
b[:, 1]  #array con la prima colonna 

array([1., 2.])

In [68]:
b.sum()

84.0

In [69]:
b.sum(axis=0)  #mi calcola la somma delle diverse colonne

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [70]:
b.sum(axis=1)  #mi calcola la somma delle diverse righe

array([28., 56.])

In [72]:
c = np.zeros((2, 3), dtype='i', order='C') #array di zeri con 2 righe e 3 colonne, tipo intero, ordinamento linguaggio C (prima alloco gli elementi della prima riga e poi la seconda riga)
#mentre se uso order=F ordino per colonna
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [73]:
c = np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [74]:
#se voglio lo stesso shape di c
d = np.zeros_like(c, dtype='f16', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [75]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [77]:
e = np.empty((2,3,2))
e  #bit in quelle allocazioni di memoria, non sono valori random!!

array([[[4.67126268e-310, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.92195027e-310, 1.58817677e-052]],

       [[5.33241631e-091, 1.31397851e-047],
        [1.53389598e-052, 5.40050475e-062],
        [3.99910963e+252, 1.46030983e-319]]])

In [79]:
e = np.empty_like((c))
e

array([[[-2000823168,       22013,          53,           0],
        [          0,           0,           0,           0],
        [          0,           0,  1953702523,  1937077345]],

       [[ 1864514082,   573317739,  1635017060,  2105227810],
        [ 1701650988,  1633968500,   975331700,   573341051],
        [ 1853189990,  1715085924,  1702063201,       32125]]],
      dtype=int32)

In [80]:
# matrice quadrata 1 nella diagonale principale e tutti gli altri uguali a 0 => matrice identità
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
g = np.linspace(5,15,12)  #da 5 a 15 (incluso) con 12 valori
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

**Metainformazioni**

In [82]:
g.size

12

In [83]:
g.itemsize  #bit usati per ogni item

8

In [84]:
#numero dimensioni
g.ndim

1

In [87]:
#tipo
g.dtype

dtype('float64')

In [88]:
# numero di bytes usati per g
g.nbytes

96

**Reshaping e Resizing**

In [90]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
g.shape

(15,)

In [92]:
np.shape(g)

(15,)

In [93]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
h = g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [95]:
# trasposta
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [97]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [100]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
np.resize(g, (3,1))  #seleziono gli elementi di g, disponendoli in 3 righe e 1 colonna

array([[0],
       [1],
       [2]])

In [99]:
np.resize(g, (1,5))  #seleziono gli elementi di g, disponendoli in 1 riga e 5 colonne

array([[0, 1, 2, 3, 4]])

In [101]:
np.resize(g, (5,4))  #riparte ciclicamente 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

**Stacking**

In [102]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [103]:
#stack orizzontale (horizzontal)
np.hstack((h, 2*h))  #la h non c'entra con il nome dell'array

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [106]:
#stack verticale (vertical)
np.vstack((h, 2*h))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

**Flattening**

In [107]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [108]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [109]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [110]:
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [113]:
for i in h.flat:
  print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [114]:
for i in h.ravel(order='F'):
   print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

In [115]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [116]:
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [117]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [118]:
(h == 5).astype(int) #se non voglio la notazione in booleano

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [119]:
(h > 4) & (h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [121]:
h[h>8]   #se voglio un array con effettivamente i valori che soddisfano la mia condizione 

array([ 9, 10, 11, 12, 13, 14])

In [122]:
h[(h > 4) & (h <= 12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
np.where(h < 7, 1, 0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [124]:
np.where(h % 2 == 0, 'pari', 'dispari')  #'pari' se soddisfo la condizione, 'dispari' altrimenti

array([['pari', 'dispari', 'pari'],
       ['dispari', 'pari', 'dispari'],
       ['pari', 'dispari', 'pari'],
       ['dispari', 'pari', 'dispari'],
       ['pari', 'dispari', 'pari']], dtype='<U7')

In [125]:
np.where(h <= 7, h*2, h/2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [127]:
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape(4,3) * 0.5

In [128]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [130]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [131]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [132]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [133]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [136]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [134]:
s = np.arange(0, 12, 4)  #da 0 a 12 con passo di 4 (con 12 escluso)
s

array([0, 4, 8])

In [135]:
r + s   #questo va bene poiché le colonne sono sempre 3

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

#Liste

In [137]:
m = [i ** 2 for i in range(5)]
m

[0, 1, 4, 9, 16]

#Map

In [139]:
def even(x):
  return x % 2 == 0

In [140]:
list(map(even, range(10)))  #in base ai valori degli indici

[True, False, True, False, True, False, True, False, True, False]

In [141]:
list(filter(even, range(10)))

[0, 2, 4, 6, 8]