<a href="https://colab.research.google.com/github/MichelaPascale/AI_Python/blob/main/PyTorchTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PyTorch Basics**

In [1]:
import torch

In [2]:
x = torch.empty(1)  # 1 è la size del tensor
print(x)

tensor([-2.2954e+18])


In [3]:
#Possiamo cambiare la size
x = torch.empty(3)  #quindi avremo un vettore a 1 dimensione e con 3 elementi
print(x)

tensor([-2.2956e+18,  3.0796e-41,  0.0000e+00])


In [4]:
# 2d
x = torch.empty(2, 3) # 2 dimensioni con 3 elementi
x

tensor([[-2.2956e+18,  3.0796e-41,  1.5975e-43],
        [ 1.3873e-43,  1.4574e-43,  6.4460e-44]])

In [7]:
# 3d
x = torch.empty(2, 2, 3)
x

tensor([[[-2.2957e+18,  3.0796e-41,  1.5975e-43],
         [ 1.3873e-43,  1.4574e-43,  6.4460e-44]],

        [[ 1.4153e-43,  1.5274e-43,  1.5695e-43],
         [ 1.6255e-43,  1.6956e-43,  0.0000e+00]]])

In [8]:
# tensor con random values
x = torch.rand(2, 2)
x

tensor([[0.8100, 0.8361],
        [0.8280, 0.6544]])

In [9]:
# tensor con tutti zero
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [10]:
# tensor con tutti uno
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [11]:
x.dtype

torch.float32

In [14]:
# per cambiare il tipo degli elementi del tensore
x = torch.ones(2, 2, dtype = torch.int) # anche torch.doubles, torch.float16
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [15]:
x.size()

torch.Size([2, 2])

In [16]:
# Possiamo costruire un tensore da una lista di dati
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

**Somma** tra gli elementi di tensori diversi

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

print('------------------------')
z = x + y
print('Sum:')
print(z)

tensor([[0.0356, 0.8010],
        [0.1820, 0.8882]])
tensor([[0.3740, 0.6978],
        [0.0204, 0.7253]])
------------------------
Sum:
tensor([[0.4096, 1.4988],
        [0.2024, 1.6135]])


In [22]:
# Oppure
z = torch.add(x,y)
z

tensor([[0.4096, 1.4988],
        [0.2024, 1.6135]])

In [23]:
# Se invece voglio modificare y con la somma di x e y
y.add_(x)   
y

'''
ATTENZIONE!!
Tutte le funzioni di Torch con un underscore (_) vanno a modificare gli 
elementi della variabile corrente, quella a cui è applicata la funzione
'''

tensor([[0.4096, 1.4988],
        [0.2024, 1.6135]])

**Differenza**

In [24]:
z = x - y
z

tensor([[-0.3740, -0.6978],
        [-0.0204, -0.7253]])

In [26]:
# Oppure
z = torch.sub(x,y)
z

tensor([[-0.3740, -0.6978],
        [-0.0204, -0.7253]])

**Moltiplicazione**

In [27]:
z = x * y
z

tensor([[0.0146, 1.2006],
        [0.0368, 1.4331]])

In [29]:
# Oppure
z = torch.mul(x,y)
z

tensor([[0.0146, 1.2006],
        [0.0368, 1.4331]])

In [ ]:
# Se voglio modificare il valore di y
y.mul_(x)
y

**Divisione**

In [31]:
z = x / y
z

tensor([[0.0869, 0.5344],
        [0.8992, 0.5505]])

In [33]:
# Oppure
z = torch.div(x,y)
z

tensor([[0.0869, 0.5344],
        [0.8992, 0.5505]])

**Slicing**

In [34]:
x = torch.rand(5,3)
x

tensor([[0.3558, 0.5236, 0.1870],
        [0.7372, 0.5362, 0.5993],
        [0.7570, 0.7813, 0.4668],
        [0.7151, 0.3361, 0.1061],
        [0.9069, 0.2347, 0.7425]])

In [35]:
print(x[:, 0])  # considero tutte le righe ma solo la colonna 0

tensor([0.3558, 0.7372, 0.7570, 0.7151, 0.9069])


In [36]:
print(x[1, :])  # considero tutta la seconda riga

tensor([0.7372, 0.5362, 0.5993])


In [37]:
print(x[1, 1])  # considero solo l'elemento alla seconda riga e alla seconda colonna

tensor(0.5362)


In [41]:
# Se ho un tensore con un solo elemento posso richiamarlo con la funzione item()
x = torch.rand(1,1)
print(x)
print(x.item())

tensor([[0.9412]])
0.9412114024162292


**Reshape**

In [42]:
x = torch.rand(4,4)
x

tensor([[0.9959, 0.3180, 0.4926, 0.1627],
        [0.1343, 0.1344, 0.3133, 0.4280],
        [0.4634, 0.3646, 0.0405, 0.5498],
        [0.8055, 0.0622, 0.8510, 0.1624]])

In [44]:
y = x.view(16)  # con una sola dimensione
y

tensor([0.9959, 0.3180, 0.4926, 0.1627, 0.1343, 0.1344, 0.3133, 0.4280, 0.4634,
        0.3646, 0.0405, 0.5498, 0.8055, 0.0622, 0.8510, 0.1624])

In [45]:
# Se non voglio inserire la dimensione o mettere i valori in una dimensione
y = x.view(-1, 8)  # quindi in questo caso ho 2 dimensioni da 8
y

tensor([[0.9959, 0.3180, 0.4926, 0.1627, 0.1343, 0.1344, 0.3133, 0.4280],
        [0.4634, 0.3646, 0.0405, 0.5498, 0.8055, 0.0622, 0.8510, 0.1624]])

In [46]:
y.size()

torch.Size([2, 8])

**Torch to Numpy**

In [47]:
import numpy as np

In [48]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [50]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [51]:
type(b)

numpy.ndarray

In [52]:
'''
ATTENZIONE!!
Se il tensore e l'array sono salvati sulla CPU e non sulla GPU, condivideranno la stessa memoria
=> se modifico uno modifico anche l'altro
'''

# Per esempio
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [53]:
b  # => anche l'array è stato modificato

array([2., 2., 2., 2., 2.], dtype=float32)

**Numpy to Torch**

In [55]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [56]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [59]:
'''
ATTENZIONE!!
Anche in questo caso se modifico uno modifico anche l'altro
'''

a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Per una variabile da ottimizzare**

In [60]:
# Se ho una variabile che voglio otimizzare allora è necessario specificare requires_grad = True
# questa dice che è necessario il calcolo dei gradienti
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

## **Autograd**
Gradient Computation